# Generated by Django 5.0.4 on 2024-05-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loai',
            fields=[
                ('MaLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoai', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.AutoField(primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('MoTa', models.CharField(max_length=500)),
                ('SoLuong', models.PositiveIntegerField()),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('HinhAnh', models.ImageField(upload_to='product')),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.loai')),
            ],
        ),
    ]
