# Generated by Django 5.0.4 on 2024-05-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MauSac',
            fields=[
                ('MaMau', models.AutoField(primary_key=True, serialize=False)),
                ('TenMau', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='MaMau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.mausac'),
            preserve_default=False,
        ),
    ]
