# Generated by Django 5.0.4 on 2024-05-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mausac_sanpham_mamau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='MaMau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.mausac'),
        ),
    ]
