# Generated by Django 5.0.4 on 2024-05-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sanpham_mamau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='MaMau',
        ),
    ]
