# Generated by Django 5.0.4 on 2024-05-31 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
